import "98.css";
import Breadcrumbs from "@/components/Breadcrumbs/Breadcrumbs";
import Navbar from "@/components/Navbar/Navbar";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "98 Weblog",
  description: "98 Weblog generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Navbar />
          <Breadcrumbs />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
