import "98.css";
import Breadcrumbs from "@/components/Breadcrumbs/Breadcrumbs";
import Navbar from "@/components/Navbar/Navbar";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "98 Weblog",
  description: "98 Weblog generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              justifyContent: "space-between",
              minHeight: "100vh",
            }}
          >
            <div>
              <Navbar />
              <Breadcrumbs />
              <main>{children}</main>
            </div>
            <div>
              <Footer />
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
